# Generated by Django 5.2.3 on 2025-06-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název týmu')),
                ('city', models.CharField(max_length=100, verbose_name='Město')),
                ('founded', models.IntegerField(verbose_name='Rok založení')),
            ],
            options={
                'verbose_name': 'Tým',
                'verbose_name_plural': 'Týmy',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('nationality', models.CharField(max_length=100, verbose_name='Národnost')),
                ('age', models.PositiveIntegerField(verbose_name='Věk')),
                ('position', models.CharField(max_length=50, verbose_name='Pozice')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fotbal.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Fotbalista',
                'verbose_name_plural': 'Fotbalisté',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum zápasu')),
                ('home_goals', models.PositiveIntegerField(verbose_name='Góly domácích')),
                ('away_goals', models.PositiveIntegerField(verbose_name='Góly hostů')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='fotbal.team', verbose_name='Hostující tým')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='fotbal.team', verbose_name='Domácí tým')),
            ],
            options={
                'verbose_name': 'Zápas',
                'verbose_name_plural': 'Zápasy',
            },
        ),
    ]
