# Generated by Django 5.2.3 on 2025-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis zápasu'),
        ),
    ]
