# Generated by Django 5.2.3 on 2025-06-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0002_match_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='fotbal.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='fotbal.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotbal.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='founded',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('x_start', models.FloatField()),
                ('y_start', models.FloatField()),
                ('x_end', models.FloatField()),
                ('y_end', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='fotbal.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='fotbal.match')),
                ('scorer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_scored', to='fotbal.player')),
            ],
        ),
    ]
