# Generated by Django 5.2.3 on 2025-06-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0003_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
